name: Install istioctl cli

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # ignore warning for this step 
    # refer - https://github.com/CumulusDS/get-yaml-paths-action/issues/7
    - name: Read istio version
      uses: cumulusds/get-yaml-paths-action@v0.1.0
      id: istio-version
      with:
        file: input.yaml
        version: foundation.istio.version

    - name: Install istioctl
      if: ${{ steps.istio-version.outputs.version }}
      uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
      with:
        version: ${{ steps.istio-version.outputs.version }}

    - name: Check istioctl version
      if: ${{ steps.istio-version.outputs.version }}
      run: |
        istioctl version --remote=false

